name: audio-enh-supervise

channels:
  - conda-forge

dependencies:
  - python=3.11.0
  - cudatoolkit
  - cudnn
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - numpy
    - scipy
    - librosa
    - h5py
    - matplotlib
    - tqdm
